name: frontend
description: Floor plan and booking management system.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^5.0.0
  # mockito: ^5.0.7
  # build_runner: ^1.11.0 #Needed for mockito
  url_launcher:
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  pdf: ^3.4.2
  downloads_path_provider: ^0.1.0 # Needed to save a PDF to a device from a mobile device
  universal_html: ^2.0.8 # Needed to save a PDF to a device from a PC
  native_pdf_view: any # Needed to display a PDF in the app
  mockito: ^5.0.13
  mailer: ^5.0.1
  mailer2: ^1.2.5
  file_picker: ^3.0.4
  objectdb: ^1.2.1+1
  build_runner: ^2.0.6
  random_string: ^2.3.1
  syncfusion_flutter_charts: ^19.2.57
  qr_flutter: ^4.0.0
  flutter_typeahead: ^3.2.0
  jitsi_meet: ^4.0.0 # Needed to implement video conferencing
  avatar_glow: ^2.0.1
  googleapis: ^5.0.1
  googleapis_auth: ^1.1.0
  onesignal_flutter: ^2.6.3
  flutter_google_places: ^0.3.0
  google_maps_flutter: ^2.0.9
  location: ^4.3.0

dependency_overrides:
  photo_view: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # To change app package name:
  # change_app_package_name: ^1.0.0
  # Then in the terminal run "flutter pub run change_app_package_name:main com.new.package.name"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/chatbot-icon.png
    - assets/images/city-silhouette.png
    - assets/images/logo.png
    - assets/images/placeholder-announcement.png
    - assets/images/placeholder-employee-image.png
    - assets/images/placeholder-notification.png
    - assets/images/placeholder-office-building.png
    - assets/images/placeholder-office-floor.png
    - assets/images/placeholder-office-room.png
    - assets/images/placeholder-pdf.png
    - assets/images/placeholder-profile-image.png
    - assets/images/placeholder-request-icon.png
    - assets/images/placeholder-shift.png
    - assets/images/warning-icon.png
    - assets/images/coffee1.jpg
    - assets/images/sick1.jpg
    - assets/images/sick2.jpg
    - assets/images/sick3.jpg
    - assets/images/sick4.jpg
    - assets/images/sick5.jpg
    - assets/images/sick6.jpg
    - assets/images/sick7.jpg
    - assets/images/sick8.jpg
    - assets/images/sick9.jpg
    - assets/images/sick10.jpg
    - assets/images/sick11.jpg
    - assets/images/sick12.jpg
    - assets/images/sick13.jpg
    - assets/images/sick14.jpg
    - assets/images/Coviduous_tutorials_using_the_app.png
    - assets/sample.pdf
    - assets/za-covid-guidelines.pdf
  # PDF fonts
    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/OpenSans-Bold.ttf
    - assets/fonts/OpenSans-Italic.ttf
    - assets/fonts/OpenSans-BoldItalic.ttf

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
